#!/usr/bin/env python3
"""Generate a conservative HIP baseline case from inspect_ref.py output."""

from __future__ import annotations

import argparse
import json
import os
import re
import shlex
import shutil
from pathlib import Path
from typing import Any


MATH_FUNCS = {
    "torch.exp": "expf",
    "torch.sqrt": "sqrtf",
    "torch.rsqrt": "rsqrtf",
    "torch.sin": "sinf",
    "torch.cos": "cosf",
    "torch.tanh": "tanhf",
    "torch.relu": "fmaxf",
}


def _load_json(path: str) -> dict[str, Any]:
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, dict):
        raise SystemExit(f"{path} must contain a JSON object")
    return data


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


def _cmd(parts: list[str | Path]) -> str:
    return " ".join(shlex.quote(str(part)) for part in parts)


def _optimizer_script(name: str) -> Path:
    skill_dir = Path(__file__).resolve().parents[1]
    optimizer_dir = skill_dir.parent / "hyhon-hip-kernel-optimizer"
    return optimizer_dir / "scripts" / name


def _dim_params(dims: dict[str, int]) -> list[str]:
    preferred = [k for k in ("M", "N", "K") if k in dims]
    rest = [k for k in dims if k not in preferred]
    return preferred + rest


def _safe_ident(name: str) -> str:
    clean = re.sub(r"\W+", "_", name.strip())
    if not clean or clean[0].isdigit():
        clean = f"v_{clean}"
    return clean


def _sanitize_expr(expr: str, tensor_args: list[str], dims: dict[str, int]) -> str | None:
    """Translate a tiny subset of Torch scalar expressions into C.

    This is intentionally narrow. Unsupported expressions return None so the
    manifest can tell the agent to repair the baseline by hand.
    """
    if not expr:
        return None
    text = expr.strip()
    text = re.sub(r"\.float\(\)", "", text)
    text = re.sub(r"\.to\([^)]*\)", "", text)
    for name in tensor_args:
        text = re.sub(rf"\b{re.escape(name)}\b(?!\s*\[)", f"{name}[i]", text)
    for dim in dims:
        text = re.sub(rf"\b{re.escape(dim)}\b", dim, text)
    text = text.replace("**", "^")
    if "^" in text:
        return None
    # Common unary calls.
    for torch_name, c_name in MATH_FUNCS.items():
        if torch_name == "torch.relu":
            text = re.sub(r"torch\.relu\(([^()]+)\)", r"fmaxf(\1, 0.0f)", text)
        else:
            text = re.sub(rf"{re.escape(torch_name)}\(([^()]+)\)", rf"{c_name}(\1)", text)
    # Allow arithmetic, identifiers, subscripts, literals, and selected funcs.
    if re.search(r"[^A-Za-z0-9_\[\]\(\)\+\-\*/\., ]", text):
        return None
    if "torch." in text or "tl." in text or ".view" in text or ".reshape" in text:
        return None
    return text


def _copy_original_ref(ref_file: str, out_dir: Path) -> str:
    src = Path(ref_file)
    dst = out_dir / "ref_original.py"
    if src.resolve() != dst.resolve():
        shutil.copy2(src, dst)
    return dst.name


def _adapter_py(analysis: dict[str, Any], output_name: str, op_kind: str, original_name: str) -> str:
    chosen = analysis.get("chosen_reference") or {}
    sig = analysis.get("signature_hint") or {}
    dims = analysis.get("dims") or {}
    fn_name = chosen.get("name") or "reference"
    tensor_args = [_safe_ident(a) for a in sig.get("tensor_args", [])]
    output_args = [_safe_ident(a) for a in sig.get("output_args", [])]
    dim_args = _dim_params(dims)
    return_style = sig.get("return_style")

    if return_style == "inplace" and output_args:
        ref_args = list(dict.fromkeys(tensor_args + dim_args))
        public_args = ref_args
        call_args = ", ".join(ref_args)
        body = f"    return _orig.{fn_name}({call_args})"
    else:
        inputs = [a for a in tensor_args if a not in output_args]
        if not inputs:
            inputs = tensor_args
        public_args = inputs + [output_name] + dim_args
        call_inputs = inputs + dim_args
        call_args = ", ".join(call_inputs)
        if op_kind == "matmul" and {"M", "N", "K"}.issubset(dims) and len(inputs) >= 2:
            a, b = inputs[:2]
            view_lines = [
                f"    {a}_v = {a}[:M * K].view(M, K)",
                f"    {b}_v = {b}[:K * N].view(K, N)",
            ]
            call_map = {a: f"{a}_v", b: f"{b}_v"}
            call_args = ", ".join(call_map.get(x, x) for x in call_inputs)
            body = "\n".join(view_lines + [
                f"    result = _orig.{fn_name}({call_args})",
                f"    {output_name}[:M * N].view(M, N).copy_(result.view(M, N))",
            ])
        else:
            body = "\n".join([
                f"    result = _orig.{fn_name}({call_args})",
                f"    {output_name}.copy_(result.reshape_as({output_name}))",
            ])

    args = ", ".join(public_args)
    return f'''# Generated by hygon-hip-baseline-generator. Edit only if the adapter
# does not match the original reference contract.
from __future__ import annotations

import importlib.util
from pathlib import Path


_ORIG_PATH = Path(__file__).with_name("{original_name}")
_SPEC = importlib.util.spec_from_file_location("_hygon_ref_original", _ORIG_PATH)
if _SPEC is None or _SPEC.loader is None:
    raise ImportError(f"cannot import {{_ORIG_PATH}}")
_orig = importlib.util.module_from_spec(_SPEC)
_SPEC.loader.exec_module(_orig)

atol = getattr(_orig, "atol", 1e-4)
rtol = getattr(_orig, "rtol", 1e-3)


def reference({args}):
{body}
'''


def _hip_signature(inputs: list[str], outputs: list[str], dims: dict[str, int]) -> str:
    parts = [f"const float* {name}" for name in inputs]
    parts.extend(f"float* {name}" for name in outputs)
    parts.extend(f"int {name}" for name in _dim_params(dims))
    return ", ".join(parts)


def _elementwise_kernel(analysis: dict[str, Any], output_name: str) -> tuple[str, list[str]]:
    sig = analysis.get("signature_hint") or {}
    dims = analysis.get("dims") or {}
    tensor_args = [_safe_ident(a) for a in sig.get("tensor_args", [])]
    output_args = [_safe_ident(a) for a in sig.get("output_args", [])]
    return_style = sig.get("return_style")
    chosen = analysis.get("chosen_reference") or {}

    if return_style == "inplace" and output_args:
        outputs = output_args
        inputs = [a for a in tensor_args if a not in outputs]
    else:
        outputs = [output_name]
        inputs = tensor_args

    if not inputs:
        inputs = ["x"]
    if not outputs:
        outputs = [output_name]

    n_name = "N" if "N" in dims else (_dim_params(dims)[0] if dims else "N")
    expr = None
    unsupported: list[str] = []
    for ret in chosen.get("return_exprs", [])[:1]:
        expr = _sanitize_expr(ret, inputs, dims)
    if expr is None:
        expr = f"{inputs[0]}[i]"
        unsupported.append("elementwise expression could not be translated; generated copy baseline")

    signature = _hip_signature(inputs, outputs, dims)
    first_out = outputs[0]
    text = f'''#include <hip/hip_runtime.h>
#include <math.h>

__global__ void baseline_kernel({signature}) {{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < {n_name}) {{
        {first_out}[i] = {expr};
    }}
}}

extern "C" void solve({signature}) {{
    dim3 block(256);
    dim3 grid(({n_name} + block.x - 1) / block.x);
    baseline_kernel<<<grid, block>>>({", ".join(inputs + outputs + _dim_params(dims))});
}}
'''
    return text, unsupported


def _matmul_kernel(analysis: dict[str, Any], output_name: str) -> tuple[str, list[str]]:
    sig = analysis.get("signature_hint") or {}
    dims = analysis.get("dims") or {}
    tensor_args = [_safe_ident(a) for a in sig.get("tensor_args", [])]
    output_args = [_safe_ident(a) for a in sig.get("output_args", [])]
    return_style = sig.get("return_style")

    if return_style == "inplace" and output_args:
        outputs = output_args[:1]
        inputs = [a for a in tensor_args if a not in outputs][:2]
    else:
        outputs = [output_name]
        inputs = tensor_args[:2]
    if len(inputs) < 2:
        inputs = (inputs + ["A", "B"])[:2]
    if not outputs:
        outputs = [output_name]
    a, b = inputs[:2]
    c = outputs[0]
    signature = _hip_signature([a, b], [c], dims)
    unsupported: list[str] = []
    if not {"M", "N", "K"}.issubset(dims):
        unsupported.append("matmul baseline assumes dims include M,N,K")
    text = f'''#include <hip/hip_runtime.h>

__global__ void baseline_matmul({signature}) {{
    int col = blockIdx.x * blockDim.x + threadIdx.x;
    int row = blockIdx.y * blockDim.y + threadIdx.y;
    if (row < M && col < N) {{
        float acc = 0.0f;
        for (int k = 0; k < K; ++k) {{
            acc += {a}[row * K + k] * {b}[k * N + col];
        }}
        {c}[row * N + col] = acc;
    }}
}}

extern "C" void solve({signature}) {{
    dim3 block(16, 16);
    dim3 grid((N + block.x - 1) / block.x, (M + block.y - 1) / block.y);
    baseline_matmul<<<grid, block>>>({", ".join([a, b, c] + _dim_params(dims))});
}}
'''
    return text, unsupported


def generate(analysis_path: str, out_dir: str, op: str, output_name: str) -> dict[str, Any]:
    analysis = _load_json(analysis_path)
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    op_kind = analysis.get("classification", {}).get("op_kind", "unknown") if op == "auto" else op
    ref_file = analysis.get("ref_file")
    if not ref_file or not os.path.isfile(ref_file):
        raise SystemExit("analysis ref_file is missing or no longer exists")

    original_name = _copy_original_ref(ref_file, out)
    _write(out / "ref_analysis.json", json.dumps(analysis, indent=2, ensure_ascii=False) + "\n")
    _write(out / "ref.py", _adapter_py(analysis, output_name, op_kind, original_name))

    unsupported = list(analysis.get("unsupported_assumptions", []))
    if op_kind == "matmul":
        kernel, extra = _matmul_kernel(analysis, output_name)
    elif op_kind == "elementwise":
        kernel, extra = _elementwise_kernel(analysis, output_name)
    else:
        kernel, extra = _elementwise_kernel(analysis, output_name)
        unsupported.append(f"op_kind={op_kind!r} is not directly supported; generated placeholder elementwise baseline")
    unsupported.extend(extra)
    _write(out / "kernel.hip", kernel)

    dims = analysis.get("dims") or {}
    ptr_size_hint = 0
    if {"M", "N", "K"}.issubset(dims):
        ptr_size_hint = max(int(dims["M"]) * int(dims["K"]), int(dims["K"]) * int(dims["N"]), int(dims["M"]) * int(dims["N"]))
    elif "N" in dims:
        ptr_size_hint = int(dims["N"])

    dim_args = " ".join(f"--{k}={v}" for k, v in dims.items())
    preflight_script = _optimizer_script("preflight.py")
    benchmark_script = _optimizer_script("benchmark.py")
    orchestrate_script = _optimizer_script("orchestrate.py")
    dims_json = json.dumps(dims, separators=(",", ":"))
    manifest = {
        "case_dir": str(out.resolve()),
        "analysis": str((out / "ref_analysis.json").resolve()),
        "kernel": str((out / "kernel.hip").resolve()),
        "ref": str((out / "ref.py").resolve()),
        "original_ref": str((out / original_name).resolve()),
        "op_kind": op_kind,
        "dims": dims,
        "ptr_size_hint": ptr_size_hint,
        "unsupported_assumptions": sorted(set(unsupported)),
        "optimizer_scripts": {
            "preflight": str(preflight_script),
            "benchmark": str(benchmark_script),
            "orchestrate": str(orchestrate_script),
        },
        "preflight_command": _cmd([
            "python",
            preflight_script,
            "--baseline",
            out / "kernel.hip",
            "--ref",
            out / "ref.py",
            "--dims",
            dims_json,
        ]),
        "benchmark_command": (
            "HIP_VISIBLE_DEVICES=<device> "
            + _cmd([
                "python",
                benchmark_script,
                out / "kernel.hip",
                "--ref",
                out / "ref.py",
                "--ptr-size",
                str(ptr_size_hint),
                "--json-out",
                out / "baseline_bench.json",
            ])
            + (f" {dim_args}" if dim_args else "")
        ),
        "orchestrate_setup_command": (
            _cmd([
                "python",
                orchestrate_script,
                "setup",
                "--baseline",
                out / "kernel.hip",
                "--ref",
                out / "ref.py",
                "--dims",
                dims_json,
                "--ptr-size",
                str(ptr_size_hint),
            ])
            + " --iterations <iterations> --branches <branches>"
        ),
    }
    _write(out / "baseline_manifest.json", json.dumps(manifest, indent=2, ensure_ascii=False) + "\n")
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate a conservative HIP baseline from ref analysis")
    parser.add_argument("--analysis", required=True)
    parser.add_argument("--out-dir", required=True)
    parser.add_argument("--op", default="auto", choices=["auto", "elementwise", "matmul", "reduction", "unknown"])
    parser.add_argument("--output-name", default="out")
    args = parser.parse_args()
    manifest = generate(args.analysis, args.out_dir, args.op, _safe_ident(args.output_name))
    print(json.dumps(manifest, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
